### PR TITLE
Set PICO_FLASH_SPI_CLKDIV=2 when building boot2

### PR DESCRIPTION
**Pull request by jannic**
The assembly files contain a configurable clock divider, with a default value of 4. The C SDK overwrites this value with 2, eg. for the rp pico:

https://github.com/raspberrypi/pico-sdk/blob/master/src/boards/include/boards/pico.h#L70

Because we didn't set that value in rp2040-boot2-rs, rust firmwares effectively ran the flash chip at half speed.

Therefore, set the preprocessor define from build.rs, to match what the C SDK does.

### CODE REVIEW

**Comment by jannic** [comment]
I wonder if this is a breaking change: While using 2 as a clock divider should normally work, if the firmware does overclocking it might have worked with a divider of 4 but would no longer be reliable with a divider of 2.

So, on the one hand, this change might break existing code, but on the other hand, that only happens if the code is already running the rp2040 out of spec.

**Review by 9names — COMMENTED** [review]
> I wonder if this is a breaking change

I think it is. As you say, most folks will be fine because they haven't messed with clocks, but we've also freely advocated overclocking as something that will basically work with every chip. A patch version bump should never break any project, and this definitely could.

**Comment by thejpster** [comment]
Fair point.

**Comment by jannic** [comment]
Would it be an option to select clkdiv using a feature flag?

build.rs:
```rust
    let clkdiv = if cfg!(feature = "fast-flash") {
        2
    } else {
        4
    };
    let output = Command::new("arm-none-eabi-gcc")
        ...
        .arg(format!("-DPICO_FLASH_SPI_CLKDIV={}", clkdiv))
```

Cargo.toml:
```toml
[features]
# Assemble the boot2 files. Requires GCC
assemble = []
# Set PICO_FLASH_SPI_CLKDIV=2 instead of 4 for
# faster flash access
fast-flash = ["assemble"]
```

**Comment by jannic** [comment]
After thinking about it a little bit longer,  this looks too complicated. Much simpler to just accept the breaking change and do the semver bump. So you only get the speed-improvement if you update the dependency, but that should be fine. It's not like people are complaining about slow flash speed.

**Comment by thejpster** [comment]
Yeah, let's bump the major.

**Review by thejpster — APPROVED** [review]

**Comment by thejpster** [comment]
Uh, this repo has both a `develop` and a `main` branch. Typically you would merge PRs into `develop` and only update `main` when you do a release.

If we're not doing that, we should delete the `develop` branch to avoid confusion.

**Comment by jannic** [comment]
> Uh, this repo has both a `develop` and a `main` branch. Typically you would merge PRs into `develop` and only update `main` when you do a release.
> 
> If we're not doing that, we should delete the `develop` branch to avoid confusion.

Sorry, I didn't notice that. Is a separate `develop` branch useful for this crate? I don't really think so, as I don't expect much development here. I agree that we should delete it if we don't use it.

**Pull request merged**
