### PR TITLE
Write build results to OUT_DIR

### LINKED ISSUE #25: build.rs writes to wrong directory
In general, build outputs should only be written to OUT_DIR.
(https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script, "Scripts should not modify any files outside of that directory.")

The existing `build.rs` also writes to CARGO_MANIFEST_DIR when the feature `assemble` is active: https://github.com/rp-rs/rp2040-boot2/blob/4c477f9e1a4ef0beff10bd3c4436f4e66fec334c/build.rs#L107-L111

While unusual, this is handy when called locally to update the pre-built binaries.

However, it becomes a problem when used as part of some dependency tree. For example, I have some firmware which depends on a local checkout of  `rp2040-boot` like this:
```
[dependency]
rp2040-boot2 = { version = "0.2", path = "/some/other/path/rp2040-boot2-rs", features=["assemble"] }
```

In this case, the build will write to `/some/other/path/rp2040-boot2-rs/bin`. This is unexpected, and might not even work. In my case, that path was not writable by the current build process, resulting in this error message:

```
error:failed to run custom build command for `rp2040-boot2 v0.2.2 (/some/other/path/rp2040-boot2-rs)`

Causedby:
 process didn't exit successfully: `/some/other/path/rp2040-project-template/target/debug/build/rp2040-boot2-ab9f999e2371819e/build-script-build` (exit status: 101)
 --- stdout
 cargo:warning=final out dir = /some/other/path/rp2040-boot2-rs/bin/

 --- stderr
 In file included from src/include/boot2_helpers/exit_from_boot2.S:10:0,
                  from src/boot2_at25sf128a.S:273:
 src/include/hardware/regs/m0plus.h:565:0: warning: "M0PLUS_CPUID_OFFSET" redefined
  #define M0PLUS_CPUID_OFFSET _u(0x0000ed00)
   
 In file included from src/include/pico/platform.h:20:0,
                  from src/include/pico.h:31,
                  from src/include/pico/asm_helper.S:7,
                  from src/boot2_at25sf128a.S:28:
 src/include/hardware/regs/addressmap.h:72:0: note: this is the location of the previous definition
  #define M0PLUS_CPUID_OFFSET 0x0000ed00
   
 In file included from src/include/boot2_helpers/exit_from_boot2.S:10:0,
                  from src/boot2_at25sf128a.S:273:
 src/include/hardware/regs/m0plus.h:742:0: warning: "M0PLUS_VTOR_OFFSET" redefined
  #define M0PLUS_VTOR_OFFSET _u(0x0000ed08)
   
 In file included from src/include/pico/platform.h:20:0,
                  from src/include/pico.h:31,
                  from src/include/pico/asm_helper.S:7,
                  from src/boot2_at25sf128a.S:28:
 src/include/hardware/regs/addressmap.h:73:0: note: this is the location of the previous definition
  #define M0PLUS_VTOR_OFFSET 0x0000ed08
   
 /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000008000
 thread 'main' panicked at 'writing padded output file: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }', /some/other/path/rp2040-boot2-rs/build.rs:99:34
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When not using a `path` dependency, it writes to paths like `~/.cargo/registry/src/github.com-1ecc6299db9ec823/rp2040-boot2-0.2.1/bin/boot2_at25sf128a.padded.bin` instead, which isn't correct either.

### PR DESCRIPTION
**Pull request by jannic**
Precompiled binaries can still be updated by setting UPDATE_PRECOMPILED_BINARIES

Fixes #25

### CODE REVIEW

**Review by 9names — APPROVED** [review]
Looks good to me. Can't test this right now but I assume this is well tested.

**Comment by jannic** [comment]
> I assume this is well tested

It would be nice if somebody using Windows could test it, as I only have Linux.

**Comment by 9names** [comment]
Tested on Windows, using prebuilt, features=assemble, and with UPDATE_COMPILED_BINARIES env-var set.
All good.

**Comment by jannic** [comment]
Thank you, @9names !

**Pull request merged**
